Feature/GHI-11-freestyle-jobs & bug/GHI-7-Remove-dummy-declarative-methods
zowe/zowe-zdevops-jenkins-plugin pull request #47
Opened 2023-07-12 04:52 UTC by callbacksin

* implemented DowloadDatasetStep method via a freestyle job
* fix the bug showing dummy methods in a build steps list
* add minor fixes

2023-07-12 08:42 UTC, callbacksin commented
related: #11 , #7

2023-07-12 16:05 UTC, VKrus approved these changes

2023-07-12 17:28 UTC, KUGDev commented on src/main/kotlin/org/zowe/zdevops/logic/DownloadOperation.kt
> +/*
Tests at least 80% of instructions

2023-07-12 17:29 UTC, KUGDev commented on src/main/kotlin/org/zowe/zdevops/utils/FieldsValidation.kt
>  }
Tests

2023-07-12 17:29 UTC, KUGDev commented on src/main/kotlin/org/zowe/zdevops/utils/miscUtils.kt
>  package org.zowe.zdevops.utils
Remove as not needed anymore

2023-08-30 11:31 UTC, KUGDev commented
classic/steps/DeleteDatasetStep.kt - 80% coverage needed
classic/steps/DeleteDatasetsByMaskStep.kt - 80% coverage needed
logic/DeleteOperation.kt - 80% coverage needed

2023-08-30 11:31 UTC, KUGDev requested changes
classic/steps/DeleteDatasetStep.kt - 80% coverage needed
classic/steps/DeleteDatasetsByMaskStep.kt - 80% coverage needed
logic/DeleteOperation.kt - 80% coverage needed

2023-09-01 16:58 UTC, KUGDev approved these changes

2023-09-15 07:55 UTC, merged